{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flappy-kray.serviceAccountName" . }}
  labels:
{{ include "flappy-kray.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end -}}
